name: Bug Report
description: Something is broken
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: What happened?
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
    validations:
      required: true
